name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - fmt
      
    steps:
      - run: exit 0

  fmt:
    name: Style check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
         components: rustfmt
         
    - name: Style server check
      run: | 
        if ! cargo fmt --check --manifest-path=server/Cargo.toml; then
          printf "Please run \`cargo fmt --check --manifest-path=server/Cargo.toml\` to ensure code style standards are met."
          exit 1
        fi
